name: Auto Remove Blocking Relationships On Issue Close

on:
  issues:
    types:
      - closed

jobs:
  remove-blocking-links:
    uses: askclara/.github/.github/workflows/remove-blocking-on-close.yml@main
    with:
      issue-number: ${{ github.event.issue.number }}
      repo: ${{ github.repository }}
    secrets:
      AC_AUTOMATION_PAT: ${{ secrets.AC_AUTOMATION_PAT }}
